# Use the official Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the local file to the container
COPY main.py .

# Run the script
CMD ["python", "./main.py"]
